Used to compare different supervised learning algorithms

In [90]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
iris=load_iris()


In [78]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [79]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["target"]=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier


In [81]:
X=df.drop(["target"],axis=1)
y=df["target"]

In [82]:
from sklearn.model_selection import cross_val_score

In [83]:
lr_score=cross_val_score(LogisticRegression(),X,y,cv=3)
lr_score

array([0.96078431, 0.92156863, 0.95833333])

In [84]:
sv_score=cross_val_score(SVC(),X,y,cv=3)
sv_score

array([0.98039216, 0.96078431, 0.97916667])

In [85]:
rf_score=cross_val_score(RandomForestClassifier(),X,y,cv=3)
rf_score

array([0.98039216, 0.92156863, 0.97916667])

In [86]:
dt_score=cross_val_score(DecisionTreeClassifier(),X,y,cv=3)
dt_score

array([0.98039216, 0.92156863, 0.97916667])

In [87]:
np.average(lr_score)

0.9468954248366014

In [88]:
np.average(sv_score)

0.9734477124183006

In [89]:
np.average(rf_score)

0.960375816993464

In [76]:
np.average(dt_score)

0.960375816993464